version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf

sphinx:
  fail_on_warning: true

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
