version: 2

formats:
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - make install
