name: Feature request
description: Suggest an idea for this project
labels: [Enhancement]

body:      
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the problem
      description: >
        Is your feature request related to a problem? Please provide a clear
        and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution
      description: >
        Please provide a clear and concise description of the solution that you
        would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: >
        Please provide a clear and concise description of any alternative
        solutions or features you have considered.
